# Generated by Django 4.2.1 on 2023-08-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producthome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
                ("price", models.FloatField()),
                ("digital", models.BooleanField(default=False, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
