# Generated by Django 4.2.1 on 2023-08-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_producthome"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="Producthome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.producthome",
            ),
        ),
    ]
